version: '3.8'

services:
  spotify-analysis:
    build: .
    container_name: spotify-playlist-analysis
    environment:
      # Spotify API credentials (required)
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      
      # Google AI credentials (required)
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - GOOGLE_GENAI_MODEL_TYPE=${GOOGLE_GENAI_MODEL_TYPE:-gemini-2.0-flash-001}
      - GOOGLE_GENAI_SYSTEM_INSTRUCTION=${GOOGLE_GENAI_SYSTEM_INSTRUCTION}
      - GOOGLE_GENAI_BASE_PROMPT=${GOOGLE_GENAI_BASE_PROMPT}
      - GOOGLE_GENAI_TEMPERATURE=${GOOGLE_GENAI_TEMPERATURE:-0.7}
      - GOOGLE_GENAI_TOP_P=${GOOGLE_GENAI_TOP_P:-0.6}
      - GOOGLE_GENAI_TOP_K=${GOOGLE_GENAI_TOP_K:-30}
      
      # Optional settings
      - AI_ANALYSIS_SAVED_AS_MARKDOWN=${AI_ANALYSIS_SAVED_AS_MARKDOWN:-True}
      - OUTPUT_FILENAME_API_DETAILS=${OUTPUT_FILENAME_API_DETAILS:-api_details}
      - OUTPUT_FILENAME_SONGS_DETAILS=${OUTPUT_FILENAME_SONGS_DETAILS:-songs_details}
    volumes:
      # Mount output directory to persist results
      - ./output:/app/output
      # Mount environment file if it exists
      - ./.env:/app/.env:ro
    command: ["python", "-m", "noviirnawati.main", "${PLAYLIST_URL}"]
    restart: "no"
    
  # Development service with volume mounting
  spotify-analysis-dev:
    build: .
    container_name: spotify-playlist-analysis-dev
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - GOOGLE_GENAI_MODEL_TYPE=${GOOGLE_GENAI_MODEL_TYPE:-gemini-2.0-flash-001}
      - GOOGLE_GENAI_SYSTEM_INSTRUCTION=${GOOGLE_GENAI_SYSTEM_INSTRUCTION}
      - GOOGLE_GENAI_BASE_PROMPT=${GOOGLE_GENAI_BASE_PROMPT}
      - GOOGLE_GENAI_TEMPERATURE=${GOOGLE_GENAI_TEMPERATURE:-0.7}
      - GOOGLE_GENAI_TOP_P=${GOOGLE_GENAI_TOP_P:-0.6}
      - GOOGLE_GENAI_TOP_K=${GOOGLE_GENAI_TOP_K:-30}
      - AI_ANALYSIS_SAVED_AS_MARKDOWN=${AI_ANALYSIS_SAVED_AS_MARKDOWN:-True}
    volumes:
      # Mount source code for development
      - .:/app
      - ./output:/app/output
    command: ["python", "-m", "noviirnawati.main", "${PLAYLIST_URL}"]
    restart: "no"
    profiles:
      - dev
