import os

AI_ANALYSIS_SAVED_AS_MARKDOWN = os.getenv('RESULT_SAVED_AS_MARKDOWN')

OUTPUT_FILENAME_API_DETAILS = os.getenv('OUTPUT_FILENAME_API_DETAILS')
OUTPUT_FILENAME_SONGS_DETAILS = os.getenv('OUTPUT_FILENAME_SONGS_DETAILS')

DATA_SCRAPING_SAVE_API_DETAILS = os.getenv('DATA_SCRAPING_SAVE_API_DETAILS')
DATA_SCRAPING_SAVE_SONGS_DETAILS = os.getenv('DATA_SCRAPING_SAVE_SONGS_DETAILS')
